from PySide6.QtCore import Qt

# the keys permitted within the keyboard library
KEYBOARD_KEYS = [
    '>', '?', '@', '[', '\\', ']', '^', '_', '`',
    'a', 'b', 'c', 'd', 'e','f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o',
    'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~',
    'accept', 'add', 'alt', 'altleft', 'altright', 'apps', 'backspace',
    'browserback', 'browserfavorites', 'browserforward', 'browserhome',
    'browserrefresh', 'browsersearch', 'browserstop', 'capslock', 'clear',
    'convert', 'ctrl', 'ctrlleft', 'ctrlright', 'decimal', 'del', 'delete',
    'divide', 'down', 'end', 'enter', 'esc', 'escape', 'execute', 'f1', 'f10',
    'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f2', 'f20',
    'f21', 'f22', 'f23', 'f24', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9',
    'final', 'fn', 'hanguel', 'hangul', 'hanja', 'help', 'home', 'insert', 'junja',
    'kana', 'kanji', 'launchapp1', 'launchapp2', 'launchmail',
    'launchmediaselect', 'left', 'modechange', 'multiply', 'nexttrack',
    'nonconvert', 'num0', 'num1', 'num2', 'num3', 'num4', 'num5', 'num6',
    'num7', 'num8', 'num9', 'numlock', 'pagedown', 'pageup', 'pause', 'pgdn',
    'pgup', 'playpause', 'prevtrack', 'print', 'printscreen', 'prntscrn',
    'prtsc', 'prtscr', 'return', 'right', 'scrolllock', 'select', 'separator',
    'shift', 'shiftleft', 'shiftright', 'sleep', 'space', 'stop', 'subtract', 'tab',
    'up', 'volumedown', 'volumemute', 'volumeup', 'win', 'winleft', 'winright', 'yen',
    'command', 'option', 'optionleft', 'optionright'
]

# the keys permitted via enums under Qt::Key
QT_KEYS = [
    Qt.Key.Key_Escape,
    Qt.Key.Key_Tab,
    Qt.Key.Key_Backtab,
    Qt.Key.Key_Backspace,	 
    Qt.Key.Key_Return,
    Qt.Key.Key_Enter,
    Qt.Key.Key_Insert,
    Qt.Key.Key_Delete,
    Qt.Key.Key_Pause,
    Qt.Key.Key_Print, 
    Qt.Key.Key_SysReq,
    Qt.Key.Key_Clear,
    Qt.Key.Key_Home,
    Qt.Key.Key_End,
    Qt.Key.Key_Left,
    Qt.Key.Key_Up,
    Qt.Key.Key_Right,
    Qt.Key.Key_Down,
    Qt.Key.Key_PageUp,
    Qt.Key.Key_PageDown,
    Qt.Key.Key_Shift,
    Qt.Key.Key_Control,
    Qt.Key.Key_Meta,
    Qt.Key.Key_Alt,
    Qt.Key.Key_AltGr,
    Qt.Key.Key_CapsLock,
    Qt.Key.Key_NumLock,
    Qt.Key.Key_ScrollLock,
    Qt.Key.Key_F1,
    Qt.Key.Key_F2,
    Qt.Key.Key_F3,
    Qt.Key.Key_F4,
    Qt.Key.Key_F5,
    Qt.Key.Key_F6,
    Qt.Key.Key_F7,
    Qt.Key.Key_F8,
    Qt.Key.Key_F9,
    Qt.Key.Key_F10,
    Qt.Key.Key_F11,
    Qt.Key.Key_F12,
    Qt.Key.Key_F13,
    Qt.Key.Key_F14,
    Qt.Key.Key_F15,
    Qt.Key.Key_F16,
    Qt.Key.Key_F17,
    Qt.Key.Key_F18,
    Qt.Key.Key_F19,
    Qt.Key.Key_F20,
    Qt.Key.Key_F21,
    Qt.Key.Key_F22,
    Qt.Key.Key_F23,
    Qt.Key.Key_F24,
    Qt.Key.Key_F25,
    Qt.Key.Key_F26,
    Qt.Key.Key_F27,
    Qt.Key.Key_F28,
    Qt.Key.Key_F29,
    Qt.Key.Key_F30,
    Qt.Key.Key_F31,
    Qt.Key.Key_F32,
    Qt.Key.Key_F33,
    Qt.Key.Key_F34,
    Qt.Key.Key_F35,
    Qt.Key.Key_Super_L,
    Qt.Key.Key_Super_R,
    Qt.Key.Key_Menu,
    Qt.Key.Key_Hyper_L,
    Qt.Key.Key_Hyper_R,
    Qt.Key.Key_Help,
    Qt.Key.Key_Direction_L,
    Qt.Key.Key_Direction_R,
    Qt.Key.Key_Space,
    Qt.Key.Key_Exclam,
    Qt.Key.Key_QuoteDbl,
    Qt.Key.Key_NumberSign,
    Qt.Key.Key_Dollar,
    Qt.Key.Key_Percent,
    Qt.Key.Key_Ampersand,
    Qt.Key.Key_Apostrophe,
    Qt.Key.Key_ParenLeft,
    Qt.Key.Key_ParenRight,
    Qt.Key.Key_Asterisk,
    Qt.Key.Key_Plus,
    Qt.Key.Key_Comma,
    Qt.Key.Key_Minus,
    Qt.Key.Key_Period,
    Qt.Key.Key_Slash,
    Qt.Key.Key_0,
    Qt.Key.Key_1,
    Qt.Key.Key_2,
    Qt.Key.Key_3,
    Qt.Key.Key_4,
    Qt.Key.Key_5,
    Qt.Key.Key_6,
    Qt.Key.Key_7,
    Qt.Key.Key_8,
    Qt.Key.Key_9,
    Qt.Key.Key_Colon,
    Qt.Key.Key_Semicolon,
    Qt.Key.Key_Less,
    Qt.Key.Key_Equal,
    Qt.Key.Key_Greater,
    Qt.Key.Key_Question,
    Qt.Key.Key_At,
    Qt.Key.Key_A,
    Qt.Key.Key_B,
    Qt.Key.Key_C,
    Qt.Key.Key_D,
    Qt.Key.Key_E,
    Qt.Key.Key_F,
    Qt.Key.Key_G,
    Qt.Key.Key_H,
    Qt.Key.Key_I,
    Qt.Key.Key_J,
    Qt.Key.Key_K,
    Qt.Key.Key_L,
    Qt.Key.Key_M,
    Qt.Key.Key_N,
    Qt.Key.Key_O,
    Qt.Key.Key_P,
    Qt.Key.Key_Q,
    Qt.Key.Key_R,
    Qt.Key.Key_S,
    Qt.Key.Key_T,
    Qt.Key.Key_U,
    Qt.Key.Key_V,
    Qt.Key.Key_W,
    Qt.Key.Key_X,
    Qt.Key.Key_Y,
    Qt.Key.Key_Z,
    Qt.Key.Key_BracketLeft,
    Qt.Key.Key_Backslash,
    Qt.Key.Key_BracketRight,
    Qt.Key.Key_AsciiCircum,
    Qt.Key.Key_Underscore,
    Qt.Key.Key_QuoteLeft,
    Qt.Key.Key_BraceLeft,
    Qt.Key.Key_Bar,
    Qt.Key.Key_BraceRight,
    Qt.Key.Key_AsciiTilde,
    Qt.Key.Key_nobreakspace,
    Qt.Key.Key_exclamdown,
    Qt.Key.Key_cent,
    Qt.Key.Key_sterling,
    Qt.Key.Key_currency,
    Qt.Key.Key_yen,
    Qt.Key.Key_brokenbar,
    Qt.Key.Key_section,
    Qt.Key.Key_diaeresis,
    Qt.Key.Key_copyright,
    Qt.Key.Key_ordfeminine,
    Qt.Key.Key_guillemotleft,
    Qt.Key.Key_notsign,
    Qt.Key.Key_hyphen,
    Qt.Key.Key_registered,
    Qt.Key.Key_macron,
    Qt.Key.Key_degree,
    Qt.Key.Key_plusminus,
    Qt.Key.Key_twosuperior,
    Qt.Key.Key_threesuperior,
    Qt.Key.Key_acute,
    Qt.Key.Key_micro,
    Qt.Key.Key_mu,
    Qt.Key.Key_paragraph,
    Qt.Key.Key_periodcentered,
    Qt.Key.Key_cedilla,
    Qt.Key.Key_onesuperior,
    Qt.Key.Key_masculine,
    Qt.Key.Key_guillemotright,
    Qt.Key.Key_onequarter,
    Qt.Key.Key_onehalf,
    Qt.Key.Key_threequarters,
    Qt.Key.Key_questiondown,
    Qt.Key.Key_Agrave,
    Qt.Key.Key_Aacute,
    Qt.Key.Key_Acircumflex,
    Qt.Key.Key_Atilde,
    Qt.Key.Key_Adiaeresis,
    Qt.Key.Key_Aring,
    Qt.Key.Key_AE,
    Qt.Key.Key_Ccedilla,
    Qt.Key.Key_Egrave,
    Qt.Key.Key_Eacute,
    Qt.Key.Key_Ecircumflex,
    Qt.Key.Key_Ediaeresis,
    Qt.Key.Key_Igrave,
    Qt.Key.Key_Iacute,
    Qt.Key.Key_Icircumflex,
    Qt.Key.Key_Idiaeresis,
    Qt.Key.Key_ETH,
    Qt.Key.Key_Ntilde,
    Qt.Key.Key_Ograve,
    Qt.Key.Key_Oacute,
    Qt.Key.Key_Ocircumflex,
    Qt.Key.Key_Otilde,
    Qt.Key.Key_Odiaeresis,
    Qt.Key.Key_multiply,
    Qt.Key.Key_Ooblique,
    Qt.Key.Key_Ugrave,
    Qt.Key.Key_Uacute,
    Qt.Key.Key_Ucircumflex,
    Qt.Key.Key_Udiaeresis,
    Qt.Key.Key_Yacute,
    Qt.Key.Key_THORN,
    Qt.Key.Key_ssharp,
    Qt.Key.Key_division,
    Qt.Key.Key_ydiaeresis,
    Qt.Key.Key_Multi_key,
    Qt.Key.Key_Codeinput,
    Qt.Key.Key_Codeinput,
    Qt.Key.Key_SingleCandidate,
    Qt.Key.Key_MultipleCandidate,
    Qt.Key.Key_PreviousCandidate,
    Qt.Key.Key_Mode_switch,
    Qt.Key.Key_Kanji,
    Qt.Key.Key_Muhenkan,
    Qt.Key.Key_Henkan,
    Qt.Key.Key_Romaji,
    Qt.Key.Key_Hiragana,
    Qt.Key.Key_Katakana,
    Qt.Key.Key_Hiragana_Katakana,
    Qt.Key.Key_Zenkaku,
    Qt.Key.Key_Hankaku,
    Qt.Key.Key_Zenkaku_Hankaku,
    Qt.Key.Key_Touroku,
    Qt.Key.Key_Massyo,
    Qt.Key.Key_Kana_Lock,
    Qt.Key.Key_Kana_Shift,
    Qt.Key.Key_Eisu_Shift,
    Qt.Key.Key_Eisu_toggle,
    Qt.Key.Key_Hangul,
    Qt.Key.Key_Hangul_Start,
    Qt.Key.Key_Hangul_End,
    Qt.Key.Key_Hangul_Hanja,
    Qt.Key.Key_Hangul_Jamo,
    Qt.Key.Key_Hangul_Romaja,
    Qt.Key.Key_Hangul_Jeonja,
    Qt.Key.Key_Hangul_Banja,
    Qt.Key.Key_Hangul_PreHanja,
    Qt.Key.Key_Hangul_PostHanja,
    Qt.Key.Key_Hangul_Special,
    Qt.Key.Key_Dead_Grave,
    Qt.Key.Key_Dead_Acute,
    Qt.Key.Key_Dead_Circumflex,
    Qt.Key.Key_Dead_Tilde,
    Qt.Key.Key_Dead_Macron,
    Qt.Key.Key_Dead_Breve,
    Qt.Key.Key_Dead_Abovedot,
    Qt.Key.Key_Dead_Diaeresis,
    Qt.Key.Key_Dead_Abovering,
    Qt.Key.Key_Dead_Doubleacute,
    Qt.Key.Key_Dead_Caron,
    Qt.Key.Key_Dead_Cedilla,
    Qt.Key.Key_Dead_Ogonek,
    Qt.Key.Key_Dead_Iota,
    Qt.Key.Key_Dead_Voiced_Sound,
    Qt.Key.Key_Dead_Semivoiced_Sound,
    Qt.Key.Key_Dead_Belowdot,
    Qt.Key.Key_Dead_Hook,
    Qt.Key.Key_Dead_Horn,
    Qt.Key.Key_Dead_Stroke,
    Qt.Key.Key_Dead_Abovecomma,
    Qt.Key.Key_Dead_Abovereversedcomma,
    Qt.Key.Key_Dead_Doublegrave,
    Qt.Key.Key_Dead_Belowring,
    Qt.Key.Key_Dead_Belowmacron,
    Qt.Key.Key_Dead_Belowcircumflex,
    Qt.Key.Key_Dead_Belowtilde,
    Qt.Key.Key_Dead_Belowbreve,
    Qt.Key.Key_Dead_Belowdiaeresis,
    Qt.Key.Key_Dead_Invertedbreve,
    Qt.Key.Key_Dead_Belowcomma,
    Qt.Key.Key_Dead_Currency,
    Qt.Key.Key_Dead_a,
    Qt.Key.Key_Dead_A,
    Qt.Key.Key_Dead_e,
    Qt.Key.Key_Dead_E,
    Qt.Key.Key_Dead_i,
    Qt.Key.Key_Dead_I,
    Qt.Key.Key_Dead_o,
    Qt.Key.Key_Dead_O,
    Qt.Key.Key_Dead_u,
    Qt.Key.Key_Dead_U,
    Qt.Key.Key_Dead_Small_Schwa,
    Qt.Key.Key_Dead_Capital_Schwa,
    Qt.Key.Key_Dead_Greek,
    Qt.Key.Key_Dead_Lowline,
    Qt.Key.Key_Dead_Aboveverticalline,
    Qt.Key.Key_Dead_Belowverticalline,
    Qt.Key.Key_Dead_Longsolidusoverlay,
    Qt.Key.Key_Back,
    Qt.Key.Key_Forward,
    Qt.Key.Key_Stop,
    Qt.Key.Key_Refresh,
    Qt.Key.Key_VolumeDown,
    Qt.Key.Key_VolumeMute,
    Qt.Key.Key_VolumeUp,
    Qt.Key.Key_BassBoost,
    Qt.Key.Key_BassUp,
    Qt.Key.Key_BassDown,
    Qt.Key.Key_TrebleUp,
    Qt.Key.Key_TrebleDown,
    Qt.Key.Key_MediaPlay,
    Qt.Key.Key_MediaStop,
    Qt.Key.Key_MediaPrevious,
    Qt.Key.Key_MediaNext,
    Qt.Key.Key_MediaRecord,
    Qt.Key.Key_MediaPause,
    Qt.Key.Key_MediaTogglePlayPause,
    Qt.Key.Key_HomePage,
    Qt.Key.Key_Favorites,
    Qt.Key.Key_Search,
    Qt.Key.Key_Standby,
    Qt.Key.Key_OpenUrl,
    Qt.Key.Key_LaunchMail,
    Qt.Key.Key_LaunchMedia,
    Qt.Key.Key_Launch0,
    Qt.Key.Key_Launch1,
    Qt.Key.Key_Launch2,
    Qt.Key.Key_Launch3,
    Qt.Key.Key_Launch4,
    Qt.Key.Key_Launch5,
    Qt.Key.Key_Launch6,
    Qt.Key.Key_Launch7,
    Qt.Key.Key_Launch8,
    Qt.Key.Key_Launch9,
    Qt.Key.Key_LaunchA,
    Qt.Key.Key_LaunchB,
    Qt.Key.Key_LaunchC,
    Qt.Key.Key_LaunchD,
    Qt.Key.Key_LaunchE,
    Qt.Key.Key_LaunchF,
    Qt.Key.Key_LaunchG,
    Qt.Key.Key_LaunchH,
    Qt.Key.Key_MonBrightnessUp,
    Qt.Key.Key_MonBrightnessDown,
    Qt.Key.Key_KeyboardLightOnOff,
    Qt.Key.Key_KeyboardBrightnessUp,
    Qt.Key.Key_KeyboardBrightnessDown,
    Qt.Key.Key_PowerOff,
    Qt.Key.Key_WakeUp,
    Qt.Key.Key_Eject,
    Qt.Key.Key_ScreenSaver,
    Qt.Key.Key_WWW,
    Qt.Key.Key_Memo,
    Qt.Key.Key_LightBulb,
    Qt.Key.Key_Shop,
    Qt.Key.Key_History,
    Qt.Key.Key_AddFavorite,
    Qt.Key.Key_HotLinks,
    Qt.Key.Key_BrightnessAdjust,
    Qt.Key.Key_Finance,
    Qt.Key.Key_Community,
    Qt.Key.Key_AudioRewind,
    Qt.Key.Key_BackForward,
    Qt.Key.Key_ApplicationLeft,
    Qt.Key.Key_ApplicationRight,
    Qt.Key.Key_Book,
    Qt.Key.Key_CD,
    Qt.Key.Key_Calculator,
    Qt.Key.Key_ToDoList,
    Qt.Key.Key_ClearGrab,
    Qt.Key.Key_Close,
    Qt.Key.Key_Copy,
    Qt.Key.Key_Cut,
    Qt.Key.Key_Display,
    Qt.Key.Key_DOS,
    Qt.Key.Key_Documents,
    Qt.Key.Key_Excel,
    Qt.Key.Key_Explorer,
    Qt.Key.Key_Game,
    Qt.Key.Key_Go,
    Qt.Key.Key_iTouch,
    Qt.Key.Key_LogOff,
    Qt.Key.Key_Market,
    Qt.Key.Key_Meeting,
    Qt.Key.Key_MenuKB,
    Qt.Key.Key_MenuPB,
    Qt.Key.Key_MySites,
    Qt.Key.Key_News,
    Qt.Key.Key_OfficeHome,
    Qt.Key.Key_Option,
    Qt.Key.Key_Paste,
    Qt.Key.Key_Phone,
    Qt.Key.Key_Calendar,
    Qt.Key.Key_Reply,
    Qt.Key.Key_Reload,
    Qt.Key.Key_RotateWindows,
    Qt.Key.Key_RotationPB,
    Qt.Key.Key_RotationKB,
    Qt.Key.Key_Save,
    Qt.Key.Key_Send,
    Qt.Key.Key_Spell,
    Qt.Key.Key_SplitScreen,
    Qt.Key.Key_Support,
    Qt.Key.Key_TaskPane,
    Qt.Key.Key_Terminal,
    Qt.Key.Key_Tools,
    Qt.Key.Key_Travel,
    Qt.Key.Key_Video,
    Qt.Key.Key_Word,
    Qt.Key.Key_Xfer,
    Qt.Key.Key_ZoomIn,
    Qt.Key.Key_ZoomOut,
    Qt.Key.Key_Away,
    Qt.Key.Key_Messenger,
    Qt.Key.Key_WebCam,
    Qt.Key.Key_MailForward,
    Qt.Key.Key_Pictures,
    Qt.Key.Key_Music,
    Qt.Key.Key_Battery,
    Qt.Key.Key_Bluetooth,
    Qt.Key.Key_WLAN,
    Qt.Key.Key_UWB,
    Qt.Key.Key_AudioForward,
    Qt.Key.Key_AudioRepeat,
    Qt.Key.Key_AudioRandomPlay,
    Qt.Key.Key_Subtitle,
    Qt.Key.Key_AudioCycleTrack,
    Qt.Key.Key_Time,
    Qt.Key.Key_Hibernate,
    Qt.Key.Key_View,
    Qt.Key.Key_TopMenu,
    Qt.Key.Key_PowerDown,
    Qt.Key.Key_Suspend,
    Qt.Key.Key_ContrastAdjust,
    Qt.Key.Key_TouchpadToggle,
    Qt.Key.Key_TouchpadOn,
    Qt.Key.Key_TouchpadOff,
    Qt.Key.Key_MicMute,
    Qt.Key.Key_Red,
    Qt.Key.Key_Green,
    Qt.Key.Key_Yellow,
    Qt.Key.Key_Blue,
    Qt.Key.Key_ChannelUp,
    Qt.Key.Key_ChannelDown,
    Qt.Key.Key_Guide,
    Qt.Key.Key_Info,
    Qt.Key.Key_Settings,
    Qt.Key.Key_MicVolumeUp,
    Qt.Key.Key_MicVolumeDown,
    Qt.Key.Key_New,
    Qt.Key.Key_Open,
    Qt.Key.Key_Find,
    Qt.Key.Key_Undo,
    Qt.Key.Key_Redo,
    Qt.Key.Key_MediaLast,
    Qt.Key.Key_unknown,
    Qt.Key.Key_Call,
    Qt.Key.Key_Camera,
    Qt.Key.Key_CameraFocus,
    Qt.Key.Key_Context1,
    Qt.Key.Key_Context2,
    Qt.Key.Key_Context3,
    Qt.Key.Key_Context4,
    Qt.Key.Key_Flip,
    Qt.Key.Key_Hangup,
    Qt.Key.Key_No,
    Qt.Key.Key_Select,
    Qt.Key.Key_Yes,
    Qt.Key.Key_ToggleCallHangup,
    Qt.Key.Key_VoiceDial,
    Qt.Key.Key_LastNumberRedial,
    Qt.Key.Key_Execute,
    Qt.Key.Key_Printer,
    Qt.Key.Key_Play,
    Qt.Key.Key_Sleep,
    Qt.Key.Key_Zoom,
    Qt.Key.Key_Exit,
    Qt.Key.Key_Cancel,
]

# list of supported key conversions, WIP
KEY_MAP = {
    Qt.Key.Key_Space: ' ', Qt.Key.Key_Exclam: '!', Qt.Key.Key_QuoteDbl: '"',  Qt.Key.Key_NumberSign: '#',
    Qt.Key.Key_Dollar: '$', Qt.Key.Key_Percent: '%', Qt.Key.Key_Ampersand: '&', Qt.Key.Key_Apostrophe: "'",
    Qt.Key.Key_ParenLeft: '(', Qt.Key.Key_ParenRight: ')', Qt.Key.Key_Asterisk: '*', Qt.Key.Key_Plus: '+',
    Qt.Key.Key_Comma: ',', Qt.Key.Key_Minus: '-', Qt.Key.Key_Period: '.', Qt.Key.Key_Slash: '/',
    Qt.Key.Key_0: '0', Qt.Key.Key_1: '1', Qt.Key.Key_2: '2', Qt.Key.Key_3: '3', Qt.Key.Key_4: '4',
    Qt.Key.Key_5: '5', Qt.Key.Key_6: '6', Qt.Key.Key_7: '7', Qt.Key.Key_8: '8', Qt.Key.Key_9: '9',
    Qt.Key.Key_Colon: ':', Qt.Key.Key_Semicolon: ';', Qt.Key.Key_Less:'<', Qt.Key.Key_Equal: '=', 
    Qt.Key.Key_Greater: '>', Qt.Key.Key_Question: '?', Qt.Key.Key_At: '@', Qt.Key.Key_BracketLeft: '[', Qt.Key.Key_Backslash: '\\',
    Qt.Key.Key_BracketRight: ']', Qt.Key.Key_AsciiCircum: '^', Qt.Key.Key_Underscore: '_', Qt.Key.Key_QuoteLeft: '`',
    Qt.Key.Key_A: 'a', Qt.Key.Key_B: 'b', Qt.Key.Key_C: 'c', Qt.Key.Key_D: 'd', Qt.Key.Key_E: 'e', Qt.Key.Key_F: 'f',
    Qt.Key.Key_G: 'g', Qt.Key.Key_H: 'h', Qt.Key.Key_I: 'i', Qt.Key.Key_J: 'j', Qt.Key.Key_K: 'k', Qt.Key.Key_L: 'l',
    Qt.Key.Key_M: 'm', Qt.Key.Key_N: 'n', Qt.Key.Key_O: 'o', Qt.Key.Key_P: 'p', Qt.Key.Key_Q: 'q', Qt.Key.Key_R: 'r',
    Qt.Key.Key_S: 's', Qt.Key.Key_T: 't', Qt.Key.Key_U: 'u', Qt.Key.Key_V: 'v', Qt.Key.Key_W: 'w', Qt.Key.Key_X: 'x',
    Qt.Key.Key_Y: 'y', Qt.Key.Key_Z: 'z',
    Qt.Key.Key_BraceLeft: '{', Qt.Key.Key_Bar: '|', Qt.Key.Key_BraceRight: '}', Qt.Key.Key_AsciiTilde: '~',
    Qt.Key.Key_Backspace: 'backspace', Qt.Key.Key_CapsLock: 'capslock',  Qt.Key.Key_Delete: 'delete',
    Qt.Key.Key_End: 'end', Qt.Key.Key_Enter: 'enter', Qt.Key.Key_Escape: 'escape',
    Qt.Key.Key_F1: 'f1', Qt.Key.Key_F2: 'f2', Qt.Key.Key_F3: 'f3', Qt.Key.Key_F4: 'f4',  Qt.Key.Key_F5: 'f5',
    Qt.Key.Key_F6: 'f6', Qt.Key.Key_F7: 'f7', Qt.Key.Key_F8: 'f8', Qt.Key.Key_F9: 'f9', Qt.Key.Key_F10: 'f10',
    Qt.Key.Key_F11: 'f11', Qt.Key.Key_F12: 'f12', Qt.Key.Key_F13: 'f13', Qt.Key.Key_F14: 'f14', Qt.Key.Key_F15: 'f15',
    Qt.Key.Key_F16: 'f16', Qt.Key.Key_F17: 'f17', Qt.Key.Key_F18: 'f18', Qt.Key.Key_F19: 'f19', Qt.Key.Key_F20: 'f20',
    Qt.Key.Key_F21: 'f21', Qt.Key.Key_F22: 'f22', Qt.Key.Key_F23: 'f23', Qt.Key.Key_F24: 'f24',
    Qt.Key.Key_Hangul: 'hangul', Qt.Key.Key_Hangul_Hanja: 'hanja', Qt.Key.Key_Hiragana_Katakana: 'kana', Qt.Key.Key_Kanji: 'kanji', Qt.Key.Key_yen: 'yen',
    Qt.Key.Key_Help: 'help', Qt.Key.Key_Home: 'home', Qt.Key.Key_Insert: 'insert', Qt.Key.Key_NumLock: 'numlock', Qt.Key.Key_Print: 'print',
    Qt.Key.Key_Return: 'return',  Qt.Key.Key_Space: 'space',
    Qt.Key.Key_Up: 'up', Qt.Key.Key_Down: 'down', Qt.Key.Key_Left: 'left', Qt.Key.Key_Right: 'right',
    Qt.Key.Key_Alt: 'alt', Qt.Key.Key_Control: 'ctrl', Qt.Key.Key_Shift: "shift"
}


def qtToKeyboardLibraryKeys(qt_key: Qt.Key) -> str:
    """
    Return the string representation of the keyboard library key using the
    Qt::Key enum.
    """
    return KEY_MAP[qt_key]


def logSupportedKeys() -> None:
    """
    Saves the keys that can be converted from Qt::Key to keyboard library keys
    in key_support.md.
    """
    with open("key_support.md", 'w') as file:
        file.write("## Supported Qt::Key Enums -> keyboard library keys:\n")
        k: Qt.Key
        v: str
        for k, v in KEY_MAP.items():
            file.write(f"{k.name} {hex(k)} {k} {v}\n")

        file.write("\n\n## Unsupported Qt::key Enums:\n")
        for k in QT_KEYS:
            if not k in KEY_MAP.keys():
                file.write(f"{k.name} {hex(k)} {k}\n")

        file.write("\n\n## Unsupported keyboard library keys:\n")
        for v in KEYBOARD_KEYS:
            if not v in KEY_MAP.values():
                file.write(f"{v}\n")


if __name__ == "__main__":
    logSupportedKeys()